name: Delta Exchange Auto-Trader
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify files
        run: |
          ls -la
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found!"
            exit 1
          fi
          
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build and Run
        env:
          DELTA_API_KEY: ${{ secrets.DELTA_API_KEY }}
          DELTA_API_SECRET: ${{ secrets.DELTA_API_SECRET }}
        run: |
          mvn --batch-mode clean package
          mvn --batch-mode exec:java -Dexec.mainClass="DeltaExchangeBracketOrder14A_BUY_SELL"
