name: Delta Exchange Auto-Trader
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download JSON library
        run: |
          mkdir -p lib
          wget -O lib/json.jar https://repo1.maven.org/maven2/org/json/json/20231013/json-20231013.jar
  - name: Compile and Run
  env:
    DELTA_API_KEY: ${{ secrets.API_KEY }}
    DELTA_API_SECRET: ${{ secrets.API_SECRET }}
  run: |
    javac -cp "lib/json.jar" DeltaExchangeBracketOrder14A_BUY_SELL.java
    java -cp ".:lib/json.jar" DeltaExchangeBracketOrder14A_BUY_SELL
