name: Delta Exchange Auto-Trader
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Caches dependencies to speed up future runs

      - name: Build and run with Maven
        env:
          DELTA_API_KEY: ${{ secrets.DELTA_API_KEY }}
          DELTA_API_SECRET: ${{ secrets.DELTA_API_SECRET }}
        run: |
          mvn --batch-mode --no-transfer-progress clean package
          mvn --batch-mode --no-transfer-progress exec:java -Dexec.mainClass="DeltaExchangeBracketOrder14A_BUY_SELL"
