name: Delta Exchange Auto-Trader
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Caches dependencies to speed up future runs

      - name: Build and package application
        env:
          DELTA_API_KEY: ${{ secrets.DELTA_API_KEY }}
          DELTA_API_SECRET: ${{ secrets.DELTA_API_SECRET }}
        run: |
          # Build the JAR file with dependencies
          mvn clean package -DskipTests

      - name: Run trading bot
        env:
          DELTA_API_KEY: ${{ secrets.DELTA_API_KEY }}
          DELTA_API_SECRET: ${{ secrets.DELTA_API_SECRET }}
        run: |
          # Execute the built JAR file
          java -jar target/short-order-bot-1.0-SNAPSHOT.jar

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            target/*.log
            target/surefire-reports/
